nome = input ("Digite um funcionário:")
empresa = input ("Digite uma empresa:")
qtde_funcionarios = int (input("Digite a quantidade de funcionários:"))
mediaMensalidade = float (input("Digite a média da mensalidade:"))
print (nome + " trabalha na empresa: " + empresa)
print("A " + empresa + " possui: ", qtde_funcionarios , " funcionarios")
print("A meida da mensalidade é de: " + str(mediaMensalidade))
print("=============================== Verifique os tipos de dados abaixo: ===============================")
print("O tipo da varaivel [nome] é: ", type(nome))
print("O tipo da varaivel [empresa] é: ", type(empresa))
print("O tipo da varaivel [qtde_funcionarios] é: ", type(qtde_funcionarios))
print("O tipo da varaivel [mediaMensalidade] é: ", type(mediaMensalidade))